DataDog/gello

CONTRIBUTING.md
app/templates/403.html
app/templates/404.html
app/templates/500.html
app/templates/_macros.html
app/templates/auth/login.html
app/templates/base.html
app/templates/boards.html
app/templates/contributors.html
app/templates/index.html
app/templates/issues.html
app/templates/pull_requests.html
app/templates/repos.html
app/templates/subscriptions.html
app/templates/trello_lists.html

- Updates the `CONTRIBUTING.md` file
- Adds the license notice to the top of all `.html` files

Add the license notice to the top of HTML files.

---

app/controllers/issues/views.py
app/controllers/pull_requests/views.py
app/controllers/trello_lists/views.py
config.py

Remove unused imports.

---

app/models/issue.py
app/models/pull_request.py
app/services/crud_service.py
app/services/issue_service.py
app/services/pull_request_service.py
app/services/trello_service.py
app/tasks/__init__.py
app/tasks/create_issue_card.py
app/tasks/create_manual_card.py
app/tasks/create_pull_request_card.py
app/tasks/create_trello_card.py
app/tasks/delete_trello_card.py
app/tasks/github_base_task.py
app/tasks/github_receiver.py
app/templates/issues.html
app/templates/pull_requests.html
migrations/versions/4ad18f16a937_add_trello_card_details_to_the_issue_.py

* Created tasks for deleting `Issue`, `PullRequest` records, and for closing trello cards when an issue or pull request is closed
* Added an abstract base class task `GitHubBaseTask`
* Updated the schema for `Issue` and `PullRequest` by including `trello_card_url` and `trello_card_id` columns
* Show the `trello_card_url` on the `Issue` and `PullRequest` views

Created tasks for deleting trello cards when an issue or pull request is `closed`.

---

app/tasks/github_receiver.py

Rename `create_card` method to `handle_card` method.

---

app/controllers/boards/views.py
app/services/__init__.py
app/services/api_service.py
app/services/board_service.py
app/services/contributor_service.py
app/services/crud_service.py
app/services/repo_service.py

Fetching data form`APIService`-derived concrete classes inserts or updates previous records. Works similar to [`first_or_create`](http://guides.rubyonrails.org/v3.2.17/active_record_querying.html#first_or_create) for `ActiveRecord`.

Added abstract `APIService`. Insert or update on `fetch`.

---

app/models/list.py
app/models/subscription.py
app/tasks/create_trello_card.py
app/tasks/delete_trello_card.py
app/tasks/github_receiver.py

Some minor PEP-8 fixes. Closes #6.

Minor PEP-8 fixes.

---

app/templates/index.html
app/templates/partials/_repos.html
app/templates/repos.html

Refactored views using repo tables ino `_repos.html` macro partial.

---

Pipfile
Pipfile.lock
config.py
tests/models/test_user.py
tests/tasks/test_github_receiver.py

Adds some unit tests for _Gello_.

Initial Test Suite Code

---

app/controllers/subscriptions/views.py
app/services/github_service.py
app/tasks/__init__.py
app/tasks/create_github_webhook.py

- Creates a GitHub webhook for a repository on the creation of a `Subscription`.
- Closes #7

Added `CreateGitHubWebhook` task to create a GitHub webhook for a pubic repository.

---

app/controllers/subscriptions/forms.py
app/controllers/subscriptions/views.py
app/models/subscription.py
app/services/subscription_service.py
app/tasks/github_receiver.py
app/templates/subscriptions.html
migrations/versions/0afe19626b22_update_autocard_for_issues_and_pull_.py

Separate `autocard` and allow the user to select if they'd like it for `issues`, pull_requests` or both.

---

.gitignore
app/__init__.py
app/api/__init__.py
app/api/boards.py
app/api/lists.py
app/api/repos.py
app/models/board.py
app/models/list.py
app/models/repo.py
app/static/styles.css
app/templates/base.html
app/templates/subscriptions.html

- Adds autocomplete via jQuery UI
- Partially completes #32

Added autocomplete functionality for creating new subscriptions.

---

app/api/repos.py
app/api/trello_members.py
app/models/board.py
app/models/list.py
app/models/repo.py
app/models/trello_member.py
app/templates/base.html
app/templates/subscribed_lists.html
app/templates/subscriptions.html

Updated autocomplete functionality.

---

app/controllers/auth/forms.py
app/controllers/boards/forms.py
app/controllers/github_members/forms.py
app/controllers/main/errors.py
app/controllers/repos/forms.py
app/controllers/subscribed_lists/forms.py
app/controllers/subscriptions/forms.py
app/controllers/subscriptions/views.py
app/controllers/trello_members/forms.py
app/models/repo.py
app/services/subscription_service.py

Form updates

---

app/controllers/subscribed_lists/forms.py
app/controllers/subscribed_lists/views.py
app/controllers/subscriptions/forms.py
app/controllers/subscriptions/views.py
app/models/repo.py
app/models/trello_member.py
app/services/trello_member_service.py
app/templates/base.html
app/templates/subscribed_lists.html
app/templates/subscriptions.html
app/templates/trello_members.html
migrations/versions/6f8827878317_add_username_for_trello_member.py

Updated autocomplete to favor unique name attributes over ids.

---

app/controllers/subscribed_lists/forms.py
app/controllers/subscribed_lists/views.py
app/controllers/subscriptions/forms.py
app/controllers/subscriptions/views.py

- Added better error messages
- Closes #50 
- Closes #52

Fixed `sqlalchemy.exc.IntegrityError` on duplicate entries by adding more form validations.

---

app/controllers/auth/forms.py
app/controllers/boards/forms.py
app/controllers/github_members/forms.py
app/controllers/repos/forms.py
app/controllers/subscribed_lists/forms.py
app/controllers/subscriptions/forms.py
app/controllers/trello_members/forms.py
app/templates/index.html
app/templates/subscribed_lists.html
app/templates/subscriptions.html

- Fixed deprecation warnings
- Minor UI updates

Fixed form deprecation warnings in by renaming the `Form`s as `FlaskForm`.

---

app/controllers/subscribed_lists/forms.py
app/controllers/subscribed_lists/views.py
app/services/subscribed_list_service.py
app/templates/subscribed_lists.html

Added `UpdateForm` and action for updating subscribed lists.

---

app/static/styles.css

UI updates.

---

app/models/repo.py
app/static/styles.css
app/templates/base.html
app/templates/boards.html
app/templates/github_members.html
app/templates/index.html
app/templates/repos.html
app/templates/subscribed_lists.html
app/templates/trello_members.html

- Some nice UI updates with regards to the way pagination was displayed

UiIupdates pagination

---

README.md

- Updates the `README.md`, by deleting content now in the wiki.

Updated `README.md` by removing content now in the `/wiki`. Updated Table of Contents links.

---

tests/services/test_board_service.py
tests/services/test_issue_service.py
tests/services/test_pull_request_service.py
tests/services/test_subscribed_list_service.py
tests/services/test_subscription_service.py
tests/utils.py

- Adds unit test for the `/services` directory

Added service test suites 

---

tests/base_test_case.py
tests/services/test_board_service.py
tests/services/test_github_member_service.py
tests/services/test_issue_service.py
tests/services/test_pull_request_service.py
tests/services/test_repo_service.py
tests/services/test_subscribed_list_service.py
tests/services/test_subscription_service.py
tests/services/test_trello_member_service.py
tests/utils.py

- Adds unit tests for the `RepoService` class.
- Adds unit tests for the `GitHubMemberService` class.
- Adds unit tests for the `TrelloMemberService` class.
- Added base class `BaseTestCase` for shared `setUp` and `tearDown` code.

Updated test suites.

---

app/services/issue_service.py
app/services/pull_request_service.py
tests/services/test_issue_service.py
tests/services/test_pull_request_service.py

- Adds `update` actions for the `PullRequestService` and `IssueService` services which are concretions for the `CRUDService` class.

Added `update` actions for `PullRequestService` and `IssueService`.

---

app/tasks/delete_trello_card.py
app/tasks/github_receiver.py
tests/tasks/test_create_manual_card.py
tests/tasks/test_create_pull_request_card.py
tests/tasks/test_delete_trello_card.py
tests/utils/database.py
tests/utils/defaults.py

- Updated the `DeleteCardObjectFromDatabase` task, and added a corresponding test suite for it.
- Added `CreateManualCardTestCase` test suite for `CreateManualCard`.
- Updated total coverage to 73%.
```
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
app/__init__.py                                   64      8    88%
app/api/__init__.py                                4      0   100%
app/api/boards.py                                 17     10    41%
app/api/lists.py                                  17     10    41%
app/api/repos.py                                  17     10    41%
app/api/trello_members.py                         17     10    41%
app/api_clients/__init__.py                        4      0 …
```

Updated celery task test cases

---

Pipfile.lock

Update Dependencies 

---

app/tasks/create_trello_card.py

Attaches a Github URL to each created card.
This gives you more metadata related to the Github issue or PR when the Github power is turned on.

Attach issue and PR URLs to cards

---

app/tasks/fetch_jira_projects.py

Added logging as a follow-up on [this PR](https://github.com/DataDog/gello/pull/109).
No way of knowing when projects are done in the logs.

Added log statement to inform finished fetching JIRA projects

---

app/services/jira_service.py

Handle paginating the JIRA responses since the JIRA API is only returning 1000 at a time.
Our org is larger than 1000

paginate since JIRA is only returning 1000 users

---

app/tasks/github_receiver.py
app/tasks/update_jira_pull_request_issue_labels.py

Fix a bug in jira issue labels update.
It wouldn't work otherwise

Fix jira issue from PR label update

---

app/tasks/append_jira_issue_labels.py
app/tasks/github_receiver.py

Fixes a race condition where the issue was deleted from the db before the closed label was applied in JIRA.
Bug report

handle adding closed label in the same thread as deleting from gello db

---

app/api_clients/jira_api_client.py

update Jira envvar
ADMIN_EMAIL is incorrect

update Jira envvar

---

.env.sample
.gitignore
Dockerfile
app/api_clients/jira_api_client.py
app/controllers/projects/forms.py
app/controllers/projects/views.py
app/services/jira_service.py
app/services/project_service.py
app/tasks/fetch_jira_projects.py
docker-compose.yml
docs/development.md
requirements.txt

Improves local development onboarding experience and allows the user to sync Jira Projects (which was previously failing due to a sync issue with Archived Projects).
Trying to diagnose and fix an issue with Gira syncing Jira Projects, but being unable to run the project locally.
I've attempted to implement a number of fixes for the Jira Project sync issue, but am unsure if it will also break when deployed in the Heroku environment due to the long-running nature of the sync task.

Improve Local Development; Allow Sync of Jira Projects
