DataDog/gello

app/models/issue.py, app/models/pull_request.py, migrations/versions/3b6e7f250153_update_trello_url_type.py
Changes the type of `trello_card_url` from fixed-size 64 character length, to variable length textfield.
Length of `trello_card_url` was sometimes longer than 64 characters.
=> Changed type of `trello_card_url` from fixed length string to textfield.

app/tasks/__init__.py, app/tasks/delete_trello_card.py, app/tasks/github_receiver.py
- Delete the reference to open issues / pull requests from Gello, but doesn't delete the card on corresponding the Trello boards
=> Only delete the reference to open issues / pull requests in Gello. Don't delete the actual trello card.

Pipfile, Pipfile.lock, app/__init__.py, config.py
Adds a boolean flag `APM_ENABLED` which defaults to `False`, which may be set to `True` if the user wishes to trace Gello with the Datadog APM.
=> Added `APM_ENABLED` option to configure Datadog tracing in Gello.

app/services/board_service.py
Added logic: before deleting outdated boards from the database, delete the lists that refer to these board_ids.
The release command `python manage.py deploy` failed with `sqlalchemy.exc.IntegrityError`, which was caused by deleting records from the boards table without first deleting records of the lists with a foreign key reference to these boards. This also causes similar errors to be thrown after clicking the "refresh boards" button.
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.NotNullViolation) null value in column "board_id" violates not-null constraint
DETAIL:  Failing row contains (966, WHAT IS HAPPENING HERE, 5c90ee025afe0d11211a48e5, 2019-03-19 …
=> Fixed Integrity Error by deleting records of lists before deleting their parent boards

app/services/trello_member_service.py, tests/services/test_trello_member_service.py
When a user clicks on `Refresh Trello Members`, a condition is implemented to check for updated `Trello_member_id` for existing users (with unchanged `username`), and commit the change accordingly.
A fetch for Trello members failed with: `sqlalchemy.exc.IntegrityError` due to a change in `trello_member_id` for an existing user. 
Because both `trello_member_id` and `username` are subject to change (despite being unique identifiers), this PR aims to cross-reference them to keep track of such changes.
```
2019-07-22T21:55:14.151715+00:00 app[web.1]: cursor.execute(statement, parameters)
2019-07-22T21:55:14.151719+00:00 app[web.1]: sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_trello_members_username" …
```
=> Update `Trello_member_id` for existing Trello members

app/services/trello_service.py, app/tasks/create_trello_card.py, app/tasks/github_receiver.py, config.py
During card creation, if its source GitHub repo is listed in `REPO_LABELS`, a (language) label would be attached to the new card (ex. an issue from repo `dd-trace-go` would result in a `Go` label in Trello).
Feature requested by APM team
New repo-label mappings can be added as key-value pairs in `REPO_LABELS` in `config.py`.
Note that this is board-agnostic, but please make sure the label name already exists in target Trello boards (new Trello labels would not be created by Gello).
Due to time constraints, the `REPO_LABELS` mapping currently exists as a dictionary in `config.py`, but going forward it would be good to store the repository-to-label relations in a database table, as well as name-to-ID mapping for labels per Trello board.
=> Add repo-dependent label to Trello card

config.py
Updates `REPO_LABELS` so that `dd-opentracing-cpp` repository includes `CPP` label.
Add a new repository with labels.
None.
=> [apm] add CPP label to `dd-opentracing-cpp`

migrations/versions/1d125da81dbf_introduce_jira_models.py, migrations/versions/4556966b899e_create_subscribed_lists_table.py
A [previous commit modified an already-run migration](https://github.com/DataDog/gello/blob/master/migrations/versions/4556966b899e_create_subscribed_lists_table.py#L38) to fix a name-length limit in postgres. However, turns out prod was using a different name `subscribed_lists_subscription_board_id_fkey`, which isn't mentioned in any of the migrations. This might have been a manual change or a difference in SQLAlchemy mangling in prod and dev. This PR makes the dev constraint name match prod.
Action Required: If you have a dev instance of Gello, you may want to recreate the database to have the newly named constraint from `subscribed_lists_subscription_board_id_subscription_repo_i_fkey ` to `subscribed_lists_subscription_board_id_fkey`, or you can modify it directly in pgAdmin.
Gello …
=> Make dev constraint name match the prod constraint name.

app/services/github_service.py, app/services/project_service.py
This PR has 2 fixes.
Fix 1: Truncates jira parent issue summaries before entering into the database due to [this constraint](https://github.com/ursulahuang/gello/blob/ursula_huang_auto_refresh_members_and_add_labels_to_issue_cards/app/models/jira_parent_issue.py#L30).
Fix 2: Added default value to [JIRA API `get_hooks()` line](https://github.com/ursulahuang/gello/blob/ursula_huang_auto_refresh_members_and_add_labels_to_issue_cards/app/services/github_service.py#L103-L107) due to [Github API Pagination API's `totalCount`](https://pygithub.readthedocs.io/en/latest/utilities.html#github.PaginatedList.PaginatedList) not working consistently with webhooks.
Fix 1: [This line querying `project.issue_types`](https://github.com/ursulahuang/gello/blob/ursula_huang_auto_refresh_members_and_add_labels …
=> Truncate issue summary; Added default value to get_hooks() to avoid exception (requires testing)

app/controllers/projects/views.py, app/tasks/__init__.py, app/tasks/fetch_jira_projects.py
Extract fetching JIRA projects into an async task to not freeze the frontend and avoid heroku worker timeouts.
Fetching large number of JIRA projects causes heroku worker timeouts.
Possible clean up: Find a better UX for informing the user that JIRA projects have been updated, currently using [flash](https://github.com/DataDog/gello/commit/26958b672f46ee6b54a8a45cae104b432de9cb95#diff-c70a76ab5c96642ee11efeaba9c96103R40).
=> Extracted fetching JIRA projects to avoid heroku worker timeouts

app/services/github_member_service.py, app/services/github_service.py, app/services/repo_service.py
Adds rate limiting delays to large lazy-loaded paginated Github API calls to adhere to [Github's rate limit of 5000 requests per hour](https://developer.github.com/v3/#rate-limiting).
`github.GithubException.RateLimitExceededException` raised in heroku release due to lazy loading of a large number of github repos.
Did not add rate limiting delays to requests fetching Github organizations in [`onboarding.py`](https://github.com/ursulahuang/gello/blob/ursula_huang_auto_refresh_members_and_add_labels_to_issue_cards/app/api/onboarding.py#L48-L54), [`onboarding/forms.py`](https://github.com/ursulahuang/gello/blob/ursula_huang_auto_refresh_members_and_add_labels_to_issue_cards/app/controllers/onboarding/forms.py#L85-L86), [`onboarding/views.py`](https://github.com/ursulahuang/gello/blob/ursula_h …
=> Adds rate limiting delays to large lazy-loaded paginated Github API calls

app/services/project_service.py, app/tasks/create_github_webhook.py, app/tasks/db_task.py, app/tasks/delete_github_webhook.py, app/tasks/fetch_jira_projects.py, app/tasks/github_base_task.py, app/tasks/upsert_github_org_webhook.py
If an exception occurs in a Celery task, the changes in the transaction do not get rolled back. 
Currently, when an exception occurs in a Celery task, nothing catches that exception and rolls back the transaction, so any subsequent Celery tasks will be poisoned with the same exception.
When an exception occurs in the web process, Flask SQLAlchemy does the rollback for you. However, Celery tasks are on a worker process rather than the web process, so the transaction never gets rolled back.
=> Catch Celery tasks that modify db with a rollback

app/services/project_service.py
Follow-up PR to [this PR that helped debug](https://github.com/DataDog/gello/pull/112) the exception and [this PR](https://github.com/DataDog/gello/pull/108) that truncated summaries before creating the SQLAlchemy object. This PR covers a missed case.
The exception `psycopg2.errors.StringDataRightTruncation: value too long for type character varying(64)` is preventing the task from finishing its function of updating and adding JIRA projects.
=> Truncated jira parent issue summary in updating function.

app/tasks/update_issue_card_labels.py
Resolves a crash in production
Resolving edge cases and crashes in production
I'm not sure what the alternative case should be here so for now I am at least preventing a potential crash. We can enhance this fix later with an alternative case if we want to handle this type of issue.
=> Verify a card id exists before update

app/tasks/create_jira_issue.py
Removes a return and enhances the printing of the JIRA API error
A very difficult to trace error when a JIRA issue does not get created correctly
This was introduced in 4fd0c822769ea65d05ef25276e2da9be2b913f77 which was a very large change set and altered the contract of no return value. For now I have made it print, but if we want to record or bubble up these errors in a different way it can be re-factored.
=> Drop explicit return for Jira Card Creation

app/services/jira_service.py
This bumps the limit to 5000 for JIRA members for the "refresh JIRA members" button.
It was only pulling 50 users into the DB.
=> bump JIRA limit to 5000

app/services/jira_service.py, app/tasks/__init__.py, app/tasks/append_jira_issue_labels.py, app/tasks/append_jira_pull_request_issue_labels.py, app/tasks/github_receiver.py
This PR adds a way to append labels to jira issues instead of overwriting them, and uses this to add the label `github_closed` to jira issues when the associated issue or PR is closed.
This would allow to use JIRA automation to automatically move issues to the `Done`, or `Closed` column when the github source of the issue is closed, while not impacting other users not interested in this feature
=> add label github_closed to issue when closing

app/tasks/github_receiver.py
When a repo was subscribed to create both Trello and JIRA objects, when a delete occurs, the deletion labeling did not occur in JIRA.
User feedback
=> don't delete record when there is a JIRA subscription

app/services/pull_request_service.py, app/tasks/delete_trello_card.py, app/tasks/github_receiver.py
When deleting PR records from the DB, only delete the one associated with the current ID (instead of all associated with the github PR id).
We were deleting items we shouldn't be.
=> delete PRs by id instead of by github PR id

app/services/issue_service.py, app/tasks/delete_trello_card.py, app/tasks/github_receiver.py
When deleting issues from the db, it previously deleted every issue from the db (JIRA and trello) by the github id. However, this prevented the JIRA workflows from running properly, since they were deleted from the DB prematurely.
Bug report.
=> delete issues from db by id

app/tasks/github_receiver.py, migrations/versions/7b85146aad79_cascade_delete_for_issues_project_key_.py
This tests two avenues of trying to improve the errors that prevent the project sync from succeeding by resolving an issue that occurs when the Jira Issue Key is not present. It also adds a simple migration to test out a theory that a lack of cascading deletes with foreign keys is preventing some code paths from continuing to execute and reverting some Postgres transactions
=> chore: add guard against null issue key; update foreign key to cascade
